import Head from "next/head";
import { About } from "../components/appcomponents/about/About";
import Introduction from "../components/appcomponents/Introduction/Introduction";
import ParticaljsBackground from "../components/genericComponents/ParticaljsBackgraound";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {/* <ParticaljsBackground /> */}
                <Introduction />
                <About />
            </main>
        </div>
    );
}
